[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/neighborhoods/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/buildings/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/rooms/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
