[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/neighborhoods/:neighborhoodId/buildings"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/neighborhoods/:neighborhoodId/buildings/:buildingId/rooms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/rooms/:roomId/panorama"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
